export const GET_LC_MODULE = 'GET_LC_MODULE'
export const GET_LC_MODULE_SUCCESS = 'GET_LC_MODULE_SUCCESS'
export const GET_LC_MODULE_FAILED = 'GET_LC_MODULE_FAILED'
 
export const UPDATE_LC_MODULE = 'UPDATE_LC_MODULE'
export const UPDATE_LC_MODULE_SUCCESS = 'UPDATE_LC_MODULE_SUCCESS'
export const UPDATE_LC_MODULE_FAILED = 'UPDATE_LC_MODULE_FAILED'