export const SUBMIT_GENERIC = 'SUBMIT_GENERIC'
export const SUBMIT_GENERIC_SUCCESS = 'SUBMIT_GENERIC_SUCCESS'
export const SUBMIT_GENERIC_FAILED = 'SUBMIT_GENERIC_FAILED'

export const GET_GENERIC = 'GET_GENERIC'
export const GET_GENERIC_SUCCESS = 'GET_GENERIC_SUCCESS'
export const GET_GENERIC_FAILED = 'GET_GENERIC_FAILED'
