export const GET_COMMODITY_SUCCESSFULL = 'GET_COMMODITY_SUCCESSFULL';
export const GET_COMMODITY_FAILED = 'GET_COMMODITY_FAILED';
export const UPDATE_COMMODITY_SUCCESSFULL = 'UPDATE_COMMODITY_SUCCESSFULL';
export const UPDATE_COMMODITY_FAILED = 'UPDATE_COMMODITY_FAILED';
export const GET_USER_SUCCESSFULL = 'GET_USER_SUCCESSFULL';
export const GET_USER_FAILED = 'GET_USER_FAILED';
export const GET_INSPECTION_DETAILS_SUCCESSFULL = 'GET_INSPECTION_DETAILS_SUCCESSFULL';
export const GET_INSPECTION_DETAILS_FAILED = 'GET_INSPECTION_DETAILS_FAILED';