export const GET_PORTS = 'GET_PORTS'
export const GET_PORTS_SUCCESS = 'GET_PORTS_SUCCESS'
export const GET_PORTS_FAILED = 'GET_PORTS_FAILED'

export const GET_ALL_PORTS = 'GET_ALL_PORTS'
export const GET_ALL_PORTS_SUCCESS = 'GET_ALL_PORTS_SUCCESS'
export const GET_ALL_PORTS_FAILED = 'GET_ALL_PORTS_FAILED'

export const UPDATE_PORTS = 'UPDATE_PORTS'
export const UPDATE_PORTS_SUCCESS = 'UPDATE_PORTS_SUCCESS'
export const UPDATE_PORTS_FAILED = 'UPDATE_PORTS_FAILED'

export const CREATE_PORTS = 'CREATE_PORTS'
export const CREATE_PORTS_SUCCESS = 'CREATE_PORTS_SUCCESS'
export const CREATE_PORTS_FAILED = 'CREATE_PORTS_FAILED'
