export const GET_COMPANY_DETAIL = 'GET_COMPANY_DETAIL'
export const GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS'
export const GET_COMPANY_DETAIL_FAILED = 'GET_COMPANY_DETAIL_FAILED'


export const UPDATE_COMPANY_DETAIL = 'UPDATE_COMPANY_DETAIL'
export const UPDATE_COMPANY_DETAIL_SUCCESS = 'UPDATE_COMPANY_DETAIL_SUCCESS'
export const UPDATE_COMPANY_DETAIL_FAILED = 'UPDATE_COMPANY_DETAIL_FAILED'


export const REFETCH_COMBINE_KARZA = 'REFETCH_COMBINE_KARZA'
export const REFETCH_COMBINE_KARZA_SUCCESS = 'REFETCH_COMBINE_KARZA_SUCCESS'
export const REFETCH_COMBINE_KARZA_FAILED = 'REFETCH_COMBINE_KARZA_FAILED'


export const GET_CREDIT_DETAIL = 'GET_CREDIT_DETAIL'
export const GET_CREDIT_DETAIL_SUCCESS = 'GET_CREDIT_DETAIL_SUCCESS'
export const GET_CREDIT_DETAIL_FAILED = 'GET_CREDIT_DETAIL_FAILED'