export const GET_COMPANY_DETAIL = 'GET_COMPANY_DETAIL'
export const GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS'
export const GET_COMPANY_DETAIL_FAILED = 'GET_COMPANY_DETAIL_FAILED'


export const UPDATE_COMPANY_DETAIL = 'UPDATE_COMPANY_DETAIL'
export const UPDATE_COMPANY_DETAIL_SUCCESS = 'UPDATE_COMPANY_DETAIL_SUCCESS'
export const UPDATE_COMPANY_DETAIL_FAILED = 'UPDATE_COMPANY_DETAIL_FAILED'