export const GET_TRANSITDETAILS = 'GET_TRANSITDETAILS'
export const GET_TRANSITDETAILS_SUCCESS = 'GET_TRANSITDETAILS_SUCCESS'
export const GET_TRANSITDETAILS_FAILED = 'GET_TRANSITDETAILS_FAILED'

export const GET_ALL_TRANSITDETAILS = 'GET_ALL_TRANSITDETAILS'
export const GET_ALL_TRANSITDETAILS_SUCCESS = 'GET_ALL_TRANSITDETAILS_SUCCESS'
export const GET_ALL_TRANSITDETAILS_FAILED = 'GET_ALL_TRANSITDETAILS_FAILED'

export const UPDATE_TRANSITDETAILS = 'UPDATE_TRANSITDETAILS'
export const UPDATE_TRANSITDETAILS_SUCCESS = 'UPDATE_TRANSITDETAILS_SUCCESS'
export const UPDATE_TRANSITDETAILS_FAILED = 'UPDATE_TRANSITDETAILS_FAILED'
