export const GET_CURRENCY = 'GET_CURRENCY'
export const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS'
export const GET_CURRENCY_FAILED = 'GET_CURRENCY_FAILED'

export const GET_ALL_CURRENCY = 'GET_ALL_CURRENCY'
export const GET_ALL_CURRENCY_SUCCESS = 'GET_ALL_CURRENCY_SUCCESS'
export const GET_ALL_CURRENCY_FAILED = 'GET_ALL_CURRENCY_FAILED'

export const UPDATE_CURRENCY = 'UPDATE_CURRENCY'
export const UPDATE_CURRENCY_SUCCESS = 'UPDATE_CURRENCY_SUCCESS'
export const UPDATE_CURRENCY_FAILED = 'UPDATE_CURRENCY_FAILED'

export const CREATE_CURRENCY = 'CREATE_CURRENCY'
export const CREATE_CURRENCY_SUCCESS = 'CREATE_CURRENCY_SUCCESS'
export const CREATE_CURRENCY_FAILED = 'CREATE_CURRENCY_FAILED'


// currency edit

export const EDIT_CURRENCY_TABLE_DATA_MASTER_SUCCESS = 'EDIT_CURRENCY_TABLE_DATA_MASTER_SUCCESS';
export const EDIT_CURRENCY_TABLE_DATA_MASTER_FAILED = 'EDIT_CURRENCY_TABLE_DATA_MASTER_FAILED';
