export const GET_LIFTING_DATA = 'GET_LIFTING_DATA'
export const GET_LIFTING_DATA_SUCCESS = 'GET_LIFTING_DATA_SUCCESS'
export const GET_LIFTING_DATA_FAILED = 'GET_LIFTING_DATA_FAILED'

export const GET_ALL_LIFTING_DATA = 'GET_ALL_LIFTING_DATA'
export const GET_ALL_LIFTING_DATA_SUCCESS = 'GET_ALL_LIFTING_DATA_SUCCESS'
export const GET_ALL_LIFTING_DATA_FAILED = 'GET_ALL_LIFTING_DATA_FAILED'

export const UPDATE_LIFTING_DATA = 'UPDATE_LIFTING_DATA'
export const UPDATE_LIFTING_DATA_SUCCESS = 'UPDATE_LIFTING_DATA_SUCCESS'
export const UPDATE_LIFTING_DATA_FAILED = 'UPDATE_LIFTING_DATA_FAILED'