export const GET_ALL_INSURANCE = "GET_ALL_INSURANCE"
export const GET_ALL_INSURANCE_SUCCESSFULL = "GET_ALL_INSURANCE_SUCCESSFULL"
export const GET_ALL_INSURANCE_FAILED = "GET_ALL_INSURANCE_FAILED"

export const CREATE_INSURANCE = "CREATE_INSURANCE"
export const CREATE_INSURANCE_SUCCESSFULL = "CREATE_INSURANCE_SUCCESSFULL"
export const CREATE_INSURANCE_FAILED = "CREATE_INSURANCE_FAILED"

export const UPDATE_INSURANCE = "UPDATE_INSURANCE"
export const UPDATE_INSURANCE_SUCCESSFULL = "UPDATE_INSURANCE_SUCCESSFULL"
export const UPDATE_INSURANCE_FAILED = "UPDATE_INSURANCE_FAILED"

export const RENEW_INSURANCE = "RENEW_INSURANCE"
export const RENEW_INSURANCE_SUCCESSFULL = "RENEW_INSURANCE_SUCCESSFULL"
export const RENEW_INSURANCE_FAILED = "RENEW_INSURANCE_FAILED"

export const UPDATE_QUOTATION = "UPDATE_QUOTATION"
export const UPDATE_QUOTATION_SUCCESSFULL = "UPDATE_QUOTATION_SUCCESSFULL"
export const UPDATE_QUOTATION_FAILED = "UPDATE_QUOTATION_FAILED"