export const GET_INSPECTION = 'GET_INSPECTION'
export const GET_INSPECTION_SUCCESS = 'GET_INSPECTION_SUCCESS'
export const GET_INSPECTION_FAILED = 'GET_INSPECTION_FAILED'

export const GET_ALL_INSPECTION = 'GET_ALL_INSPECTION'
export const GET_ALL_INSPECTION_SUCCESS = 'GET_ALL_INSPECTION_SUCCESS'
export const GET_ALL_INSPECTION_FAILED = 'GET_ALL_INSPECTION_FAILED'

export const UPDATE_INSPECTION = 'UPDATE_INSPECTION'
export const UPDATE_INSPECTION_SUCCESS = 'UPDATE_INSPECTION_SUCCESS'
export const UPDATE_INSPECTION_FAILED = 'UPDATE_INSPECTION_FAILED'

export const GET_UPDATED_DATE = 'GET_UPDATED_DATE'
