export const GET_GONOGO = 'GET_GONOGO'
export const GET_GONOGO_SUCCESS = 'GET_GONOGO_SUCCESS'
export const GET_GONOGO_FAILED = 'GET_GONOGO_FAILED'

export const GET_ALL_GONOGO = 'GET_ALL_GONOGO'
export const GET_ALL_GONOGO_SUCCESS = 'GET_ALL_GONOGO_SUCCESS'
export const GET_ALL_GONOGO_FAILED = 'GET_ALL_GONOGO_FAILED'

export const UPDATE_GONOGO = 'UPDATE_GONOGO'
export const UPDATE_GONOGO_SUCCESS = 'UPDATE_GONOGO_SUCCESS'
export const UPDATE_GONOGO_FAILED = 'UPDATE_GONOGO_FAILED'

export const CREATE_GONOGO = 'CREATE_GONOGO'
export const CREATE_GONOGO_SUCCESS = 'CREATE_GONOGO_SUCCESS'
export const CREATE_GONOGO_FAILED = 'CREATE_GONOGO_FAILED'