export const GET_COUNTRY = 'GET_COUNTRY'
export const GET_COUNTRY_SUCCESS = 'GET_COUNTRY_SUCCESS'
export const GET_COUNTRY_FAILED = 'GET_COUNTRY_FAILED'

export const GET_ALL_COUNTRY = 'GET_ALL_COUNTRY'
export const GET_ALL_COUNTRY_SUCCESS = 'GET_ALL_COUNTRY_SUCCESS'
export const GET_ALL_COUNTRY_FAILED = 'GET_ALL_COUNTRY_FAILED'

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY'
export const UPDATE_COUNTRY_SUCCESS = 'UPDATE_COUNTRY_SUCCESS'
export const UPDATE_COUNTRY_FAILED = 'UPDATE_COUNTRY_FAILED'

export const CREATE_COUNTRY = 'CREATE_COUNTRY'
export const CREATE_COUNTRY_SUCCESS = 'CREATE_COUNTRY_SUCCESS'
export const CREATE_COUNTRY_FAILED = 'CREATE_COUNTRY_FAILED'
