export const PLACE_ORDER = "PLACE_ORDER"
export const PLACE_ORDER_SUCCESSFULL = "PLACE_ORDER_SUCCESSFULL"
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED"
export const PLACED_ORDER_ROUTED = "PLACED_ORDER_ROUTED" 