export const UPDATE_CREDIT = "UPDATE_CREDIT"
export const UPDATE_CREDIT_SUCCESSFULL = "UPDATE_CREDIT_SUCCESSFULL"
export const UPDATE_CREDIT_FAILED = "UPDATE_CREDIT_FAILED"

export const UPDATE_ORDER = "UPDATE_ORDER"
export const UPDATE_ORDER_SUCCESSFULL = "UPDATE_ORDER_SUCCESSFULL"
export const UPDATE_ORDER_FAILED = "UPDATE_ORDER_FAILED"

export const SEARCH_LEADS = "SEARCH_LEADS"
export const SEARCH_LEADS_SUCCESSFULL = "SEARCH_LEADS_SUCCESSFULL"
export const SEARCH_LEADS_FAILED = "SEARCH_LEADS_FAILED"