export const GET_INTERNAL_COMPANIES = 'GET_INTERNAL_COMPANIES'
export const GET_INTERNAL_COMPANIES_SUCCESS = 'GET_INTERNAL_COMPANIES_SUCCESS'
export const GET_INTERNAL_COMPANIES_FAILED = 'GET_INTERNAL_COMPANIES_FAILED'

export const GET_ALL_INTERNAL_COMPANIES = 'GET_ALL_INTERNAL_COMPANIES'
export const GET_ALL_INTERNAL_COMPANIES_SUCCESS = 'GET_ALL_INTERNAL_COMPANIES_SUCCESS'
export const GET_ALL_INTERNAL_COMPANIES_FAILED = 'GET_ALL_INTERNAL_COMPANIES_FAILED'

export const UPDATE_INTERNAL_COMPANIES = 'UPDATE_INTERNAL_COMPANIES'
export const UPDATE_INTERNAL_COMPANIES_SUCCESS = 'UPDATE_INTERNAL_COMPANIES_SUCCESS'
export const UPDATE_INTERNAL_COMPANIES_FAILED = 'UPDATE_INTERNAL_COMPANIES_FAILED'

export const CREATE_INTERNAL_COMPANIES = 'CREATE_INTERNAL_COMPANIES'
export const CREATE_INTERNAL_COMPANIES_SUCCESS = 'CREATE_INTERNAL_COMPANIES_SUCCESS'
export const CREATE_INTERNAL_COMPANIES_FAILED = 'CREATE_INTERNAL_COMPANIES_FAILED'
