export const GET_BREADCRUMB_DATA = 'GET_BREADCRUMB_DATA'
export const CLEAR_BREADCRUMB_DATA = 'CLEAR_BREADCRUMB_DATA'

export const SET_CURRENCY = 'SET_CURRENCY'
export const GET_CURRENCY = 'GET_CURRENCY'

export const SET_UNIT = 'SET_UNIT'
export const GET_UNIT = 'GET_UNIT'
