export const GET_COUNTRIES_MASTERS = 'GET_COUNTRIES_MASTERS'
export const GET_COUNTRIES_MASTERS_SUCCESS = 'GET_COUNTRIES_MASTERS_SUCCESS'
export const GET_COUNTRIES_MASTERS_FAILURE = 'GET_COUNTRIES_MASTERS_FAILURE'

export const GET_PORTS_MASTERS = 'GET_PORTS_MASTERS'
export const GET_PORTS_MASTERS_SUCCESS = 'GET_PORTS_MASTERS_SUCCESS'
export const GET_PORTS_MASTERS_FAILURE = 'GET_PORTS_MASTERS_FAILURE'

export const GET_COMMODITIES_MASTERS = 'GET_COMMODITIES_MASTERS'
export const GET_COMMODITIES_MASTERS_SUCCESS = 'GET_COMMODITIES_MASTERS_SUCCESS'
export const GET_COMMODITIES_MASTERS_FAILURE = 'GET_COMMODITIES_MASTERS_FAILURE'

export const GET_DOCUMENTS_MASTERS = 'GET_DOCUMENTS_MASTERS'
export const GET_DOCUMENTS_MASTERS_SUCCESS = 'GET_DOCUMENTS_MASTERS_SUCCESS'
export const GET_DOCUMENTS_MASTERS_FAILURE = 'GET_DOCUMENTS_MASTERS_FAILURE'

export const GET_CURRENCY_MASTERS = 'GET_CURRENCY_MASTERS'
export const GET_CURRENCY_MASTERS_SUCCESS = 'GET_CURRENCY_MASTERS_SUCCESS'
export const GET_CURRENCY_MASTERS_FAILURE = 'GET_CURRENCY_MASTERS_FAILURE'

export const GET_INTERNAL_COMPANIES_MASTERS = 'GET_INTERNAL_COMPANIES_MASTERS'
export const GET_INTERNAL_COMPANIES_MASTERS_SUCCESS = 'GET_INTERNAL_COMPANIES_MASTERS_SUCCESS'
export const GET_INTERNAL_COMPANIES_MASTERS_FAILURE = 'GET_INTERNAL_COMPANIES_MASTERS_FAILURE'

export const GET_VENDORS_MASTERS = 'GET_VENDORS_MASTERS'
export const GET_VENDORS_MASTERS_SUCCESS = 'GET_VENDORS_MASTERS_SUCCESS'
export const GET_VENDORS_MASTERS_FAILURE = 'GET_VENDORS_MASTERS_FAILURE'

export const GET_BANKS_MASTERS = 'GET_BANKS_MASTERS'
export const GET_BANKS_MASTERS_SUCCESS = 'GET_BANKS_MASTERS_SUCCESS'
export const GET_BANKS_MASTERS_FAILURE = 'GET_BANKS_MASTERS_FAILURE'

export const GET_BANK_BRANCHES_MASTERS = 'GET_BANK_BRANCHES_MASTERS'
export const GET_BANK_BRANCHES_MASTERS_SUCCESS = 'GET_BANK_BRANCHES_MASTERS_SUCCESS'
export const GET_BANK_BRANCHES_MASTERS_FAILURE = 'GET_BANK_BRANCHES_MASTERS_FAILURE'

export const GET_PINCODES_MASTERS = 'GET_PINCODES_MASTERS'
export const GET_PINCODES_MASTERS_SUCCESS = 'GET_PINCODES_MASTERS_SUCCESS'
export const GET_PINCODES_MASTERS_FAILURE = 'GET_PINCODES_MASTERS_FAILURE'
