export const GET_COUNTRIES_MASTERS = 'GET_COUNTRIES_MASTERS';
export const GET_COUNTRIES_MASTERS_SUCCESS = 'GET_COUNTRIES_MASTERS_SUCCESS';
export const GET_COUNTRIES_MASTERS_FAILURE = 'GET_COUNTRIES_MASTERS_FAILURE';

export const GET_PORTS_MASTERS = 'GET_PORTS_MASTERS';
export const GET_PORTS_MASTERS_SUCCESS = 'GET_PORTS_MASTERS_SUCCESS';
export const GET_PORTS_MASTERS_FAILURE = 'GET_PORTS_MASTERS_FAILURE';
