export const GET_COUNTRIES_MASTERS = 'GET_COUNTRIES_MASTERS';
export const GET_COUNTRIES_MASTERS_SUCCESS = 'GET_COUNTRIES_MASTERS_SUCCESS';
export const GET_COUNTRIES_MASTERS_FAILURE = 'GET_COUNTRIES_MASTERS_FAILURE';

export const GET_COMMODITY_MASTERS = 'GET_COMMODITY_MASTERS';
export const GET_COMMODITY_MASTERS_SUCCESS = 'GET_COMMODITY_MASTERS_SUCCESS';
export const GET_COMMODITY_MASTERS_FAILURE = 'GET_COMMODITY_MASTERS_FAILURE';

export const GET_GONOGO_MASTERS = 'GET_GONOGO_MASTERS';
export const GET_GONOGO_MASTERS_SUCCESS = 'GET_GONOGO_MASTERS_SUCCESS';
export const GET_GONOGO_MASTERS_FAILURE = 'GET_GONOGO_MASTERS_FAILURE';

export const GET_PORTS_MASTERS = 'GET_PORTS_MASTERS';
export const GET_PORTS_MASTERS_SUCCESS = 'GET_PORTS_MASTERS_SUCCESS';
export const GET_PORTS_MASTERS_FAILURE = 'GET_PORTS_MASTERS_FAILURE';

export const GET_COMMODITIES_MASTERS = 'GET_COMMODITIES_MASTERS';
export const GET_COMMODITIES_MASTERS_SUCCESS = 'GET_COMMODITIES_MASTERS_SUCCESS';
export const GET_COMMODITIES_MASTERS_FAILURE = 'GET_COMMODITIES_MASTERS_FAILURE';

export const GET_DOCUMENTS_MASTERS = 'GET_DOCUMENTS_MASTERS';
export const GET_DOCUMENTS_MASTERS_SUCCESS = 'GET_DOCUMENTS_MASTERS_SUCCESS';
export const GET_DOCUMENTS_MASTERS_FAILURE = 'GET_DOCUMENTS_MASTERS_FAILURE';

export const GET_CURRENCY_MASTERS = 'GET_CURRENCY_MASTERS';
export const GET_CURRENCY_MASTERS_SUCCESS = 'GET_CURRENCY_MASTERS_SUCCESS';
export const GET_CURRENCY_MASTERS_FAILURE = 'GET_CURRENCY_MASTERS_FAILURE';

export const GET_INTERNAL_COMPANIES_MASTERS = 'GET_INTERNAL_COMPANIES_MASTERS';
export const GET_INTERNAL_COMPANIES_MASTERS_SUCCESS = 'GET_INTERNAL_COMPANIES_MASTERS_SUCCESS';
export const GET_INTERNAL_COMPANIES_MASTERS_FAILURE = 'GET_INTERNAL_COMPANIES_MASTERS_FAILURE';

export const GET_VENDORS_MASTERS = 'GET_VENDORS_MASTERS';
export const GET_VENDORS_MASTERS_SUCCESS = 'GET_VENDORS_MASTERS_SUCCESS';
export const GET_VENDORS_MASTERS_FAILURE = 'GET_VENDORS_MASTERS_FAILURE';

export const GET_BANKS_MASTERS = 'GET_BANKS_MASTERS';
export const GET_BANKS_MASTERS_SUCCESS = 'GET_BANKS_MASTERS_SUCCESS';
export const GET_BANKS_MASTERS_FAILURE = 'GET_BANKS_MASTERS_FAILURE';

export const GET_BANK_BRANCHES_MASTERS = 'GET_BANK_BRANCHES_MASTERS';
export const GET_BANK_BRANCHES_MASTERS_SUCCESS = 'GET_BANK_BRANCHES_MASTERS_SUCCESS';
export const GET_BANK_BRANCHES_MASTERS_FAILURE = 'GET_BANK_BRANCHES_MASTERS_FAILURE';

export const GET_PINCODES_MASTERS = 'GET_PINCODES_MASTERS';
export const GET_PINCODES_MASTERS_SUCCESS = 'GET_PINCODES_MASTERS_SUCCESS';
export const GET_PINCODES_MASTERS_FAILURE = 'GET_PINCODES_MASTERS_FAILURE';

// Masters Users Queue
export const GET_MASTER_USERS_QUEUE_RECORDS_SUCCESSFULL = 'GET_MASTER_USERS_QUEUE_RECORDS_SUCCESSFULL';
export const GET_MASTER_USERS_QUEUE_RECORDS_FAILED = 'GET_MASTER_USERS_QUEUE_RECORDS_FAILED';

// Masters Users Queue Search & Filter
export const FILTER_USERS_QUEUE = 'FILTER_USERS_QUEUE';
export const FILTER_USERS_QUEUE_SUCCESSFULL = 'FILTER_USERS_QUEUE_SUCCESSFULL';
export const FILTER_USERS_QUEUE_FAILED = 'FILTER_USERS_QUEUE_FAILED';

// Masters PORT Queue 
export const GET_MASTER_PORTS_QUEUE_RECORDS_SUCCESSFULL = 'GET_MASTER_PORTS_QUEUE_RECORDS_SUCCESSFULL';
export const GET_MASTER_PORTS_QUEUE_RECORDS_FAILED = 'GET_MASTER_PORTS_QUEUE_RECORDS_FAILED';

// Masters Ports Queue Search & Filter
export const FILTER_PORTS_QUEUE = 'FILTER_PORTS_QUEUE';
export const FILTER_PORTS_QUEUE_SUCCESSFULL = 'FILTER_PORTS_QUEUE_SUCCESSFULL';
export const FILTER_PORTS_QUEUE_FAILED = 'FILTER_PORTS_QUEUE_FAILED';


// Master Add Port
export const CREATE_PORT_MASTER_SUCCESS = 'CREATE_PORT_MASTER_SUCCESS';
export const CREATE_PORT_MASTER_FAILED = 'CREATE_PORT_MASTER_FAILED';
