export const GET_VESSEL = 'GET_VESSEL'
export const GET_VESSEL_SUCCESS = 'GET_VESSEL_SUCCESS'
export const GET_VESSEL_FAILED = 'GET_VESSEL_FAILED'

export const GET_ALL_VESSEL = 'GET_ALL_VESSEL'
export const GET_ALL_VESSEL_SUCCESS = 'GET_ALL_VESSEL_SUCCESS'
export const GET_ALL_VESSEL_FAILED = 'GET_ALL_VESSEL_FAILED'

export const UPDATE_VESSEL = 'UPDATE_VESSEL'
export const UPDATE_VESSEL_SUCCESS = 'UPDATE_VESSEL_SUCCESS'
export const UPDATE_VESSEL_FAILED = 'UPDATE_VESSEL_FAILED'