export const GET_BREADCRUMB_DATA = 'GET_BREADCRUMB_DATA'
export const CLEAR_BREADCRUMB_DATA = 'CLEAR_BREADCRUMB_DATA'

export const IS_LOADING = 'IS_LOADING'
export const NOT_LOADING = 'NOT_LOADING'


