export const GET_FORWARDHEDGING = 'GET_FORWARDHEDGING'
export const GET_FORWARDHEDGING_SUCCESS = 'GET_FORWARDHEDGING_SUCCESS'
export const GET_FORWARDHEDGING_FAILED = 'GET_FORWARDHEDGING_FAILED'

export const GET_ALL_FORWARDHEDGING = 'GET_ALL_FORWARDHEDGING'
export const GET_ALL_FORWARDHEDGING_SUCCESS = 'GET_ALL_FORWARDHEDGING_SUCCESS'
export const GET_ALL_FORWARDHEDGING_FAILED = 'GET_ALL_FORWARDHEDGING_FAILED'

export const UPDATE_FORWARDHEDGING = 'UPDATE_FORWARDHEDGING'
export const UPDATE_FORWARDHEDGING_SUCCESS = 'UPDATE_FORWARDHEDGING_SUCCESS'
export const UPDATE_FORWARDHEDGING_FAILED = 'UPDATE_FORWARDHEDGING_FAILED'
