export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const UPDATE_SUPPLIER_SUCCESSFULL = 'UPDATE_SUPPLIER_SUCCESSFULL';
export const UPDATE_SUPPLIER_FAILED = 'UPDATE_SUPPLIER_FAILED';

export const GET_SUPPLIER = 'GET_SUPPLIER';
export const GET_SUPPLIER_SUCCESSFULL = 'GET_SUPPLIER_SUCCESSFULL';
export const GET_SUPPLIER_FAILED = 'GET_SUPPLIER_FAILED';


export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';
export const GET_ALL_SUPPLIER_SUCCESSFULL = 'GET_ALL_SUPPLIER_SUCCESSFULL';
export const GET_ALL_SUPPLIER_FAILED = 'GET_ALL_SUPPLIER_FAILED';
