export const CREATE_SUPPLIER = 'CREATE_SUPPLIER';
export const CREATE_SUPPLIER_SUCCESSFULL = 'CREATE_SUPPLIER_SUCCESSFULL';
export const CREATE_SUPPLIER_FAILED = 'CREATE_SUPPLIER_FAILED';

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const UPDATE_SUPPLIER_SUCCESSFULL = 'UPDATE_SUPPLIER_SUCCESSFULL';
export const UPDATE_SUPPLIER_FAILED = 'UPDATE_SUPPLIER_FAILED';

export const GET_SUPPLIER = 'GET_SUPPLIER';
export const GET_SUPPLIER_SUCCESSFULL = 'GET_SUPPLIER_SUCCESSFULL';
export const GET_SUPPLIER_FAILED = 'GET_SUPPLIER_FAILED';

export const GET_ALL_SUPPLIER = 'GET_ALL_SUPPLIER';
export const GET_ALL_SUPPLIER_SUCCESSFULL = 'GET_ALL_SUPPLIER_SUCCESSFULL';
export const GET_ALL_SUPPLIER_FAILED = 'GET_ALL_SUPPLIER_FAILED';

export const CLEAR_SUPPLIER = 'CLEAR_SUPPLIER';

export const UPLOAD_SUPPLIER_DOC = 'UPLOAD_SUPPLIER_DOC';
export const UPLOAD_SUPPLIER_DOC_SUCCESSFULL = 'UPLOAD_SUPPLIER_DOC_SUCCESSFULL';
export const UPLOAD_SUPPLIER_DOC_FAILED = 'UPLOAD_SUPPLIER_DOC_FAILED';

export const DELETE_SUPPLIER_DOC = 'DELETE_SUPPLIER_DOC';
export const DELETE_SUPPLIER_DOC_SUCCESSFULL = 'DELETE_SUPPLIER_DOC_SUCCESSFULL';
export const DELETE_SUPPLIER_DOC_FAILED = 'DELETE_SUPPLIER_DOC_FAILED';

export const SEARCH_SUPPLIER = 'SEARCH_SUPPLIER';
export const SEARCH_SUPPLIER_SUCCESSFULL = 'SEARCH_SUPPLIER_SUCCESSFULL';
export const SEARCH_SUPPLIER_FAILED = 'SEARCH_SUPPLIER_FAILED';
