export const GET_ALL_MARGINMONEY = "GET_ALL_MARGINMONEY"
export const GET_ALL_MARGINMONEY_SUCCESSFULL = "GET_ALL_MARGINMONEY_SUCCESSFULL"
export const GET_ALL_MARGINMONEY_FAILED = "GET_ALL_MARGINMONEY_FAILED"