export const GET_ALL_MARGINMONEY = "GET_ALL_MARGINMONEY"
export const GET_ALL_MARGINMONEY_SUCCESSFULL = "GET_ALL_MARGINMONEY_SUCCESSFULL"
export const GET_ALL_MARGINMONEY_FAILED = "GET_ALL_MARGINMONEY_FAILED"

export const UPDATE_MARGINMONEY = "UPDATE_MARGINMONEY"
export const UPDATE_MARGINMONEY_SUCCESSFULL = "UPDATE_MARGINMONEY_SUCCESSFULL"
export const UPDATE_MARGINMONEY_FAILED = "UPDATE_MARGINMONEY_FAILED"