export const CHANGE_THEME = 'CHANGE_THEME'
export const CHANGE_THEME_SUCCESS = 'CHANGE_THEME_SUCCESS'

export const PAGE_NAME = 'PAGE_NAME'

export const DYNAMIC_PAGE = 'DYNAMIC_PAGE'

export const DYNAMIC_ORDER = 'DYNAMIC_ORDER'

export const CHANGE_CURRENCY = 'CHANGE_CURRENCY'
