export const REGISTER_BUYER = "REGISTER_BUYER"
export const REGISTER_BUYER_SUCCESS = "REGISTER_BUYER_SUCCESS"
export const REGISTER_BUYER_FAILED = "REGISTER_BUYER_FAILED"


export const UPDATE_BUYER = "UPDATE_BUYER"
export const UPDATE_BUYER_SUCCESSFULL = "UPDATE_BUYER_SUCCESSFULL"
export const UPDATE_BUYER_FAILED = "UPDATE_BUYER_FAILED"


export const DELETE_BUYER = "DELETE_BUYER"
export const DELETE_BUYER_SUCCESSFULL = "DELETE_BUYER_SUCCESSFULL"
export const DELETE_BUYER_FAILED = "DELETE_BUYER_FAILED"


export const GET_BUYER = "GET_BUYER"
export const GET_BUYER_SUCCESSFULL = "GET_BUYER_SUCCESSFULL"
export const GET_BUYER_FAILED = "GET_BUYER_FAILED"

export const GET_ALL_BUYER = "GET_ALL_BUYER"
export const GET_ALL_BUYER_SUCCESSFULL = "GET_ALL_BUYER_SUCCESSFULL"
export const GET_ALL_BUYER_FAILED = "GET_ALL_BUYER_FAILED"

export const GET_ALL_ORDER = "GET_ALL_ORDER"
export const GET_ALL_ORDER_SUCCESSFULL = "GET_ALL_ORDER_SUCCESSFULL"
export const GET_ALL_ORDER_FAILED = "GET_ALL_ORDER_FAILED"

export const SET_BUYER = "SET_BUYER"
export const SET_DOCUMENT = "SET_DOCUMENT"

export const GET_GST = "GET_GST"
export const GET_GST_SUCCESS = "GET_GST_SUCCESS"
export const GET_GST_FAILED = "GET_GST_FAILED"

export const UPDATE_PRIVILEGED_BUYER = "UPDATE_PRIVILEGED_BUYER"
export const UPDATE_PRIVILEGED_BUYER_SUCCESS = "UPDATE_PRIVILEGED_BUYER_SUCCESS"
export const UPDATE_PRIVILEGED_BUYER_FAILED = "UPDATE_PRIVILEGED_BUYER_FAILED"
