export const REGISTER_BUYER = "REGISTER_BUYER"
export const REGISTER_BUYER_SUCCESS = "REGISTER_BUYER_SUCCESS"
export const REGISTER_BUYER_FAILED = "REGISTER_BUYER_FAILED"


export const UPDATE_BUYER = "UPDATE_BUYER"
export const UPDATE_BUYER_SUCCESSFULL = "UPDATE_BUYER_SUCCESSFULL"
export const UPDATE_BUYER_FAILED = "UPDATE_BUYER_FAILED"


export const DELETE_BUYER = "DELETE_BUYER"
export const DELETE_BUYER_SUCCESSFULL = "DELETE_BUYER_SUCCESSFULL"
export const DELETE_BUYER_FAILED = "DELETE_BUYER_FAILED"


export const GET_BUYER = "GET_BUYER"
export const GET_BUYER_SUCCESSFULL = "GET_BUYER_SUCCESSFULL"
export const GET_BUYER_FAILED = "GET_BUYER_FAILED"

export const SET_BUYER = "SET_BUYER"
export const SET_DOCUMENT = "SET_DOCUMENT"