export const GET_DELIVERY = 'GET_DELIVERY'
export const GET_DELIVERY_SUCCESS = 'GET_DELIVERY_SUCCESS'
export const GET_DELIVERY_FAILED = 'GET_DELIVERY_FAILED'

export const GET_ALL_DELIVERY = 'GET_ALL_DELIVERY'
export const GET_ALL_DELIVERY_SUCCESS = 'GET_ALL_DELIVERY_SUCCESS'
export const GET_ALL_DELIVERY_FAILED = 'GET_ALL_DELIVERY_FAILED'

export const UPDATE_DELIVERY = 'UPDATE_DELIVERY'
export const UPDATE_DELIVERY_SUCCESS = 'UPDATE_DELIVERY_SUCCESS'
export const UPDATE_DELIVERY_FAILED = 'UPDATE_DELIVERY_FAILED'
