export const GET_DOCUMENT = 'GET_DOCUMENT'
export const GET_DOCUMENT_SUCCESS = 'GET_DOCUMENT_SUCCESS'
export const GET_DOCUMENT_FAILED = 'GET_DOCUMENT_FAILED'

export const GET_ALL_DOCUMENT = 'GET_ALL_DOCUMENT'
export const GET_ALL_DOCUMENT_SUCCESS = 'GET_ALL_DOCUMENT_SUCCESS'
export const GET_ALL_DOCUMENT_FAILED = 'GET_ALL_DOCUMENT_FAILED'

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT'
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS'
export const UPDATE_DOCUMENT_FAILED = 'UPDATE_DOCUMENT_FAILED'

export const CREATE_DOCUMENT = 'CREATE_DOCUMENT'
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const CREATE_DOCUMENT_FAILED = 'CREATE_DOCUMENT_FAILED'

//Document Edit
export const EDIT_DOCUMENT_TABLE_DATA_MASTER_SUCCESS = 'EDIT_DOCUMENT_TABLE_DATA_MASTER_SUCCESS';
export const EDIT_DOCUMENT_TABLE_DATA_MASTER_FAILED = 'EDIT_DOCUMENT_TABLE_DATA_MASTER_FAILED';