export const GET_CUSTOM_CLEARANCE = 'GET_CUSTOM_CLEARANCE'
export const GET_CUSTOM_CLEARANCE_SUCCESS = 'GET_CUSTOM_CLEARANCE_SUCCESS'
export const GET_CUSTOM_CLEARANCE_FAILED = 'GET_CUSTOM_CLEARANCE_FAILED'

export const GET_ALL_CUSTOM_CLEARANCE = 'GET_ALL_CUSTOM_CLEARANCE'
export const GET_ALL_CUSTOM_CLEARANCE_SUCCESS = 'GET_ALL_CUSTOM_CLEARANCE_SUCCESS'
export const GET_ALL_CUSTOM_CLEARANCE_FAILED = 'GET_ALL_CUSTOM_CLEARANCE_FAILED'

export const UPDATE_CUSTOM_CLEARANCE = 'UPDATE_CUSTOM_CLEARANCE'
export const UPDATE_CUSTOM_CLEARANCE_SUCCESS = 'UPDATE_CUSTOM_CLEARANCE_SUCCESS'
export const UPDATE_CUSTOM_CLEARANCE_FAILED = 'UPDATE_CUSTOM_CLEARANCE_FAILED'
