export const GET_COMMODITY = 'GET_COMMODITY';
export const GET_COMMODITY_SUCCESS = 'GET_COMMODITY_SUCCESS';
export const GET_COMMODITY_FAILED = 'GET_COMMODITY_FAILED';

export const GET_ALL_COMMODITY = 'GET_ALL_COMMODITY';
export const GET_ALL_COMMODITY_SUCCESS = 'GET_ALL_COMMODITY_SUCCESS';
export const GET_ALL_COMMODITY_FAILED = 'GET_ALL_COMMODITY_FAILED';

export const UPDATE_COMMODITY = 'UPDATE_COMMODITY';
export const UPDATE_COMMODITY_SUCCESS = 'UPDATE_COMMODITY_SUCCESS';
export const UPDATE_COMMODITY_FAILED = 'UPDATE_COMMODITY_FAILED';
